coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 0.1
    patch:
      default:
        enabled: yes
        target: auto
        threshold: 0.1
    ignore:
      - "model"
      - "dto"

    changes: false



comment:
  layout: "header, diff"
  behavior: default
