name: JavaCI

on: [push]

jobs:
  build:
    env:
      CODECOV_TOKEN: '5e9a20a4-cf81-4342-b3b3-237fa4875ff3'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build && ./gradlew jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        name: RoadmapApp
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
